### ISSUE TITLE
部署时出现了一个问题，我这边是查看docker的日志看见的

### ISSUE THREAD

**Issue by KroFin** [shuyangzhang/Kyouka#30]
```
2023-07-16 11:19:02.615 | ERROR    | app.task.interval_tasks:keep_bproxy_alive:97 - bproxy is not available, error msg: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://bproxy.shuyangzhang.repl.co/'), traceback: Traceback (most recent call last):
  File "/Kyouka/app/task/interval_tasks.py", line 93, in keep_bproxy_alive
    resp_json = await r.json()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://bproxy.shuyangzhang.repl.co/')

2023-07-16 11:19:02.615 | ERROR    | app.task.interval_tasks:keep_bproxy_alive:98 - bproxy is not alive now
```

如何解决？

**Comment by KroFin** [comment]
已解决
通过博主提供的bproxy本地搭建解决
参考:https://github.com/shuyangzhang/bilibili_proxy/tree/master
